version: '3'

services:
  nginx:
      container_name: nginx
      build: 
        context: nginx
      restart: unless-stopped
      ports:
        - "8080:80"
      depends_on:
        - app
      networks:
        - net-node

  app:
    container_name: app
    build:
      context: node
    networks:
      - net-node
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 --init-file /data/application/init.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ~/proj/mysql-data:/var/lib/mysql
      - ./node/init.sql:/data/application/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 33060:3306
    networks:
      - net-node

networks:
  net-node:
    driver: bridge